eureka:
  client:
    service-url:
      default-zone: http://eureka:password@localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
server:
  port: 8080
spring:
  application:
    name: api-gateway
  devtools:
    restart:
      enabled: true
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/microservices-realm
          jwk-set-uri: http://localhost:8181/realms/microservices-realm/protocol/openid-connect/certs
